const datav1 = [
  {
    id: 113841842,
    numero_antigo: null,
    numero_novo: "0010922-27.2019.5.03.0002",
    is_cnj: 1,
    enviado_trimon_em: "2021-12-24 21:24:38",
    created_at: "2019-12-17 01:58:57",
    updated_at: "2019-12-17 01:58:57",
    origem_tribunal_id: 14,
    filtrado_em: null,
    enviado_nursery_em: null,
    tipo_envolvido: "ADVOGADO",
    quantidade_movimentacoes_envolvido_faz_parte: 4,
    taxa_movimentacoes_envolvido_faz_parte: 1,
    diario_sigla: "TRT-3",
    diario_nome: "TRT da 3ª Região (Minas Gerais)",
    estado: "MG",
    data_movimentacoes: "16/12/2019 a 17/02/2020",
    quantidade_movimentacoes: 4,
    envolvidos_ultima_movimentacao: [
      {
        id: 49881,
        nome: "Liliane Schurig Fernandes",
        objeto_type: "Pessoa",
        pivot_tipo: "ADVOGADO",
        pivot_outros: "NAO",
        pivot_extra_nome: null,
        link: "https://www.escavador.com/sobre/9924882/liliane-schurig-fernandes",
        link_api: "https://api.escavador.com/api/v1/pessoas/9677849",
        nome_sem_filtro: "Liliane Schurig Fernandes",
        envolvido_tipo: "Advogado",
        envolvido_extra_nome: "",
        oab: "203691/SP",
        advogado_de: null,
      },
      {
        id: 185360,
        nome: "Dilma Silva Passos",
        objeto_type: "Pessoa",
        pivot_tipo: "ADVOGADO",
        pivot_outros: "NAO",
        pivot_extra_nome: null,
        link: "https://www.escavador.com/sobre/9963207/dilma-silva-passos",
        link_api: "https://api.escavador.com/api/v1/pessoas/9716886",
        nome_sem_filtro: "Dilma Silva Passos",
        envolvido_tipo: "Advogado",
        envolvido_extra_nome: "",
        oab: "137884/MG",
        advogado_de: null,
      },
      {
        id: 585808,
        nome: "Vito Palo Neto",
        objeto_type: "Pessoa",
        pivot_tipo: "ADVOGADO",
        pivot_outros: "NAO",
        pivot_extra_nome: null,
        link: "https://www.escavador.com/sobre/10033129/vito-palo-neto",
        link_api: "https://api.escavador.com/api/v1/pessoas/9787905",
        nome_sem_filtro: "Vito Palo Neto",
        envolvido_tipo: "Advogado",
        envolvido_extra_nome: "",
        oab: "165230/SP",
        advogado_de: null,
      },
      {
        id: 6818690,
        nome: "Ricardo Schettino de Castilho",
        objeto_type: "Pessoa",
        pivot_tipo: "PERITO",
        pivot_outros: "NAO",
        pivot_extra_nome: null,
        link: "https://www.escavador.com/sobre/17840307/ricardo-schettino-de-castilho",
        link_api: "https://api.escavador.com/api/v1/pessoas/17617945",
        nome_sem_filtro: "Ricardo Schettino de Castilho",
        envolvido_tipo: "Perito",
        envolvido_extra_nome: "",
        oab: "",
        advogado_de: null,
      },
      {
        id: 29254685,
        nome: "Kitchens Decorações Planejamento de Interiores e Comércio Ltda",
        objeto_type: "Instituicao",
        pivot_tipo: "RÉU",
        pivot_outros: "NAO",
        pivot_extra_nome: null,
        link: "https://www.escavador.com/sobre/272067491/kitchens-decoracoes-planejamento-de-interiores-e-comercio-ltda",
        link_api: "https://api.escavador.com/api/v1/instituicoes/8066464",
        nome_sem_filtro:
          "Kitchens Decorações Planejamento de Interiores e Comércio Ltda",
        envolvido_tipo: "Réu",
        envolvido_extra_nome: "",
        oab: "",
        advogado_de: null,
      },
      {
        id: 70673488,
        nome: "Grazielle Carvalho Costa Soares",
        objeto_type: "Pessoa",
        pivot_tipo: "AUTOR",
        pivot_outros: "NAO",
        pivot_extra_nome: null,
        link: "https://www.escavador.com/sobre/712382292/grazielle-carvalho-costa-soares",
        link_api: "https://api.escavador.com/api/v1/pessoas/75108438",
        nome_sem_filtro: "Grazielle Carvalho Costa Soares",
        envolvido_tipo: "Autor",
        envolvido_extra_nome: "",
        oab: "",
        advogado_de: null,
      },
    ],
    link: "https://www.escavador.com/processos/113841842/processo-0010922-2720195030002-do-trt-da-3-regiao",
    link_api: "https://api.escavador.com/api/v1/processos/113841842",
    url: {
      id: 712382290,
      slug: "processo-0010922-2720195030002-do-trt-da-3-regiao",
      objeto_type: "Processo",
      objeto_id: 113841842,
      redirect: null,
      created_at: "2019-12-17T01:58:57.000000Z",
      anuncio_ocultado_em: null,
    },
  },
];

const datav2 = [
  {
    numero_cnj: "1000893-11.2022.5.02.0005",
    titulo_polo_ativo: "Wanderley Rodrigues Nunes",
    titulo_polo_passivo: "Ala Turca Delicias Ltda",
    ano_inicio: 2022,
    data_inicio: "2022-06-29",
    estado_origem: {
      nome: "São Paulo",
      sigla: "SP",
    },
    data_ultima_movimentacao: "2022-10-20",
    quantidade_movimentacoes: 116,
    fontes_tribunais_estao_arquivadas: false,
    data_ultima_verificacao: "2023-03-01T01:13:15+00:00",
    tempo_desde_ultima_verificacao: "há 6 meses",
    tipo_match: null,
    fontes: [
      {
        id: 2094,
        processo_fonte_id: 74321310,
        outros_numeros: [],
        descricao: "TRT-2 - 1º grau",
        nome: "Tribunal Regional do Trabalho da 2ª Região",
        sigla: "TRT-2",
        tipo: "TRIBUNAL",
        data_inicio: "2022-06-29",
        data_ultima_movimentacao: "2022-08-30",
        segredo_justica: false,
        arquivado: null,
        status_predito: "ATIVO",
        grau: 1,
        grau_formatado: "Primeiro Grau",
        fisico: null,
        sistema: "PJE",
        capa: {
          classe: "Ação Trabalhista - Rito Sumaríssimo",
          assunto: "Adicional de Horas Extras",
          assuntos_normalizados: [
            {
              id: 1263,
              nome: "DIREITO DO TRABALHO",
              nome_com_pai: "DIREITO DO TRABALHO",
              path_completo: "DIREITO DO TRABALHO",
              bloqueado: false,
            },
            {
              id: 6870,
              nome: "Horas Extras",
              nome_com_pai: "Duração do Trabalho > Horas Extras",
              path_completo:
                "DIREITO DO TRABALHO > Direito Individual do Trabalho  > Duração do Trabalho > Horas Extras",
              bloqueado: false,
            },
          ],
          assunto_principal_normalizado: {
            id: 6888,
            nome: "Adicional de Horas Extras",
            nome_com_pai: "Horas Extras > Adicional de Horas Extras",
            path_completo:
              "DIREITO DO TRABALHO > Direito Individual do Trabalho  > Duração do Trabalho > Horas Extras > Adicional de Horas Extras",
            bloqueado: false,
          },
          area: "Trabalhista",
          orgao_julgador: "5ª Vara do Trabalho de São Paulo",
          situacao: null,
          valor_causa: {
            valor: "34236.7100",
            moeda: null,
            valor_formatado: "34.236,71",
          },
          data_distribuicao: "2022-06-29",
          data_arquivamento: null,
          informacoes_complementares: [
            {
              tipo: "Outros Assuntos",
              valor: "DIREITO DO TRABALHO\nDuração do Trabalho\nHoras Extras",
            },
            {
              tipo: "Justiça Gratuita",
              valor: "Sim",
            },
            {
              tipo: "Digital",
              valor: "True",
            },
            {
              tipo: "Outros Assuntos",
              valor: "DIREITO DO TRABALHO\nDuração do Trabalho\nHoras Extras",
            },
          ],
        },
        url: "https://pje.trt2.jus.br/consultaprocessual/detalhe-processo/10008931120225020005",
        tribunal: {
          id: 13,
          nome: "Tribunal Regional do Trabalho da 2ª Região",
          sigla: "TRT-2",
          categoria: null,
        },
        quantidade_envolvidos: 4,
        quantidade_movimentacoes: 108,
        data_ultima_verificacao: "2023-03-01T01:13:15+00:00",
        envolvidos: [
          {
            nome: "Wanderley Rodrigues Nunes",
            quantidade_processos: 2,
            tipo_pessoa: "FISICA",
            advogados: [
              {
                nome: "Jacqueline dos Santos",
                quantidade_processos: 1770,
                tipo_pessoa: "FISICA",
                prefixo: null,
                sufixo: null,
                tipo: "Advogado",
                tipo_normalizado: "Advogado",
                polo: "ADVOGADO",
                cpf: "23026803839",
                cnpj: null,
                oabs: [
                  {
                    uf: "SP",
                    tipo: "ADVOGADO",
                    numero: 324151,
                  },
                ],
              },
            ],
            prefixo: null,
            sufixo: null,
            tipo: "AUTOR",
            tipo_normalizado: "Autor",
            polo: "ATIVO",
            cpf: "33409744894",
            cnpj: null,
          },
          {
            nome: "Ala Turca Delicias Ltda",
            quantidade_processos: 3,
            tipo_pessoa: "JURIDICA",
            advogados: [
              {
                nome: "Vito Palo Neto",
                quantidade_processos: 485,
                tipo_pessoa: "FISICA",
                prefixo: null,
                sufixo: null,
                tipo: "Advogado",
                tipo_normalizado: "Advogado",
                polo: "ADVOGADO",
                cpf: "10796547807",
                cnpj: null,
                oabs: [
                  {
                    uf: "SP",
                    tipo: "ADVOGADO",
                    numero: 165230,
                  },
                ],
              },
            ],
            prefixo: null,
            sufixo: null,
            tipo: "Réu",
            tipo_normalizado: "Réu",
            polo: "PASSIVO",
            cpf: null,
            cnpj: "38313234000161",
          },
        ],
      },
      {
        id: 22050,
        processo_fonte_id: 420331443,
        outros_numeros: [],
        descricao: "Diário Eletrônico da Justiça do Trabalho (TRT-2)",
        nome: "Diário Eletrônico da Justiça do Trabalho (TRT-2)",
        sigla: "TRT-2",
        tipo: "DIARIO_OFICIAL",
        data_inicio: "2022-06-30",
        data_ultima_movimentacao: "2022-10-20",
        segredo_justica: null,
        arquivado: null,
        status_predito: null,
        grau: 1,
        grau_formatado: "Primeiro Grau",
        fisico: null,
        sistema: "Site",
        capa: null,
        url: null,
        tribunal: {
          id: 13,
          nome: "Tribunal Regional do Trabalho da 2ª Região",
          sigla: "TRT-2",
          categoria: null,
        },
        quantidade_envolvidos: 4,
        quantidade_movimentacoes: 8,
        data_ultima_verificacao: "2022-10-20T03:06:00+00:00",
        envolvidos: [
          {
            nome: "Jacqueline dos Santos",
            quantidade_processos: 1770,
            tipo_pessoa: "FISICA",
            prefixo: null,
            sufixo: null,
            tipo: "Advogado",
            tipo_normalizado: "Advogado",
            polo: "ADVOGADO",
            cpf: null,
            cnpj: null,
          },
          {
            nome: "Ala Turca Delicias Ltda",
            quantidade_processos: 3,
            tipo_pessoa: "JURIDICA",
            prefixo: null,
            sufixo: null,
            tipo: "RECLAMADO",
            tipo_normalizado: "Reclamado",
            polo: "PASSIVO",
            cpf: null,
            cnpj: "38313234000161",
          },
          {
            nome: "Wanderley Rodrigues Nunes",
            quantidade_processos: 2,
            tipo_pessoa: "FISICA",
            prefixo: null,
            sufixo: null,
            tipo: "RECLAMANTE",
            tipo_normalizado: "Reclamante",
            polo: "ATIVO",
            cpf: null,
            cnpj: null,
          },
          {
            nome: "Vito Palo Neto",
            quantidade_processos: 485,
            tipo_pessoa: "FISICA",
            prefixo: null,
            sufixo: null,
            tipo: "Advogado",
            tipo_normalizado: "Advogado",
            polo: "ADVOGADO",
            cpf: "10796547807",
            cnpj: null,
          },
        ],
      },
    ],
  },
];

const userOABs = [{ uf: "SP", number: "165230" }];

const resultV2 = datav2.map((item) => {
  const [tribunal, diario] = item.fontes;

  const advogados = [];

  const clientes = tribunal.envolvidos
    .filter((item) => {
      return item.advogados.some((advogado) => {
        const hasAdvogado = advogados.some(({ cpf }) => cpf === advogado.cpf);
        const isUserProfile = userOABs.some(({ number }) =>
          advogado.oabs.some(({ numero }) => numero == number)
        );

        if (!hasAdvogado && isUserProfile)
          advogados.push({ nome: advogado.nome, cpf: advogado.cpf });

        return isUserProfile;
      });
    })
    .map((item) => ({
      nome: item.nome,
      isPJ: !!item.cnpj,
      tipoPessoa: item.tipo_pessoa,
      documento: !!item.cnpj ? item.cnpj : item.cpf,
      quantidadeProcessos: item.quantidade_processos,
    }));

  return {
    clientes,
    advogados,
    cnj: item.numero_cnj,
    capaJSON: tribunal.capa,
    fonteNome: tribunal.descricao,
    poloAtivo: item.titulo_polo_ativo,
    poloPassivo: item.titulo_polo_passivo,
    arquivado: item.fontes_tribunais_estao_arquivadas,
  };
});

console.log("MODEL ", JSON.stringify(resultV2));
